[package]
name = "kittygame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy-alloc = { version = "0.4.1", optional = true }
num = "0.4.1"



[features]
# default = ["buddy-alloc"]
